/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *j
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "clock.h"
#include "abstraction.h"

uint32_t check_ccr = 0;
uint8_t angle = 0;

typedef enum {
	CHECK_BUTTON,
	SERVO_UP,
	SERVO_DOWN
}state_t;

state_t state = CHECK_BUTTON;


int main(void)
{
	clock_setup();
	gpio_setup();
	tim_init();
	tim_start();

	while(1){
		
		switch (state){
		case CHECK_BUTTON:
			if (button_read()){
				state = SERVO_UP;
			}
			break;
		case SERVO_UP:
			angle += 10;
			if (angle >=180){
				angle = 180;
				state = SERVO_DOWN;
			}
			servo_set_angle(angle);
			delay_ms(200);
			break;
		case SERVO_DOWN:
			if(angle < 10){
				angle = 0;
				state = CHECK_BUTTON;
			}else{
				angle -= 10;
			}
			servo_set_angle(angle);
			delay_ms(200);
			break;
		}
	}
}


